config/routes.rb
Rails.application.routes.draw do

  # Admin routes
  constraints subdomain: "#{ENV['ADMIN_SUBDOMAIN']}" do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  # API Routes
  namespace :api, constraints: { subdomain: "#{ENV['API_SUBDOMAIN']}" }, path: '/', defaults: { format: :json } do

    # API V1
    api_version(module: 'V1', header: { name: 'Accept', value: 'application/vnd.cervezaya.com; version=1' }, default: true) do

      with_options only: :index do |r|
        r.resources :types
        r.resources :sizes
        r.resources :promotions
        r.resources :brands
      end

      resources :bars, only: [:index, :show] do
        resources :opinions, only: [:index, :create]
      end

      resources :users, only: [:show, :create, :update, :destroy] do
        resources :favorites, only: [:index, :create, :destroy]
        resources :recents, only: [:index, :create]
        resources :ranks, only: [:show, :create]
      end

      resources :contacts, :only => [:create]

    end

    # API V2
    api_version(module: 'V2', header: { name: 'Accept', value: 'application/vnd.cervezaya.com; version=2' }) do

      with_options only: :index do |r|
        r.resources :types
        r.resources :sizes
        r.resources :brands
        r.resources :zones
        r.resources :promotions
      end

      resources :bars, only: [:index, :show] do
        resources :opinions, only: [:index, :create]
      end

      resources :users, only: [:show, :create, :update, :destroy] do
        resources :favorites, only: [:index, :create, :destroy]
        resources :recents, only: [:index, :create]
        resources :favorites_zones, only: [:index, :create, :destroy]
        resources :recents_zones, only: [:index, :create]
        resources :favorites_brands, only: [:index, :create, :destroy]
        resources :recents_brands, only: [:index, :create]
        resources :ranks, only: [:show, :create]
        resources :contacts, :only => [:create]
      end

      resources :countries, only: [:index]
      resources :cities, only: [:index]

    end
  end

  # Landing routes
  root 'welcome#index'

  get 'bares', to: 'static#business'
  get 'prensa', to: 'static#press'
  get 'legal', to: 'static#legal'
  get 'contacto', to: 'static#contact'

  # Mailer routes
  match '/business_contact', to: 'contact#bussines_mail', via: 'post'
  match '/ios_contact', to: 'contact#ios_mail', via: 'post'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.slim
.header
  nav.navbar
    .content-header.content
      .content-header-navigation
        .img-logo
          = link_to image_tag("logo.png"), root_path
        ul.nav-items.pull-right
          li
            = link_to "¿TIENES UN BAR?", bares_path, class: 'navbar-link'
          li
            = link_to "PRENSA", prensa_path, class: 'navbar-link'
          / li
            / = link_to "BLOG", '#', class: 'navbar-link'
          li
            = link_to "CONTACTO", contacto_path, class: 'navbar-link'
      .content-header-title
        h2.header-title La forma inteligente de beber cerveza.
        h4 Dínos qué te apetece tomar y nosotros te diremos dónde.
      // FeedBack Form
      .content-feedback.hide
        = form_tag(ios_contact_path) do
          .row
            .col-md-8.col-md-offset-2
              h3 CervezaYa aún no está en la App Store. ¿Quieres que te avisemos cuando esté?
              .col-md-6
                = email_field_tag 'email', nil, placeholder: "Escribe aquí tu mail...", required: true
              .col-md-6
                button.content-informame type="submit"
            - if notice
              .col-md-8.col-md-offset-2
                p.message = notice
      // AppStore & PlayStore Boxes
      .content-header-link
        .row
          .col-md-6.col-md-offset-3
            .col-md-6
              .content-app-store
            .col-md-6
              a href="https://play.google.com/store/apps/details?id=com.cervezaya.cervezaya" id="marketAndroid"
                .content-play-store

// Start Section 1
.section-1
  .content
    .col-md-4
      .img-phone
        = image_tag "phone_1.png", class: 'phone-one'
    .col-md-8
      .text-phone-one
        h1 La cerveza es algo serio.
        p CervezaYa es la aplicación móvil que te permite beber cerveza de manera inteligente. ¿Cuál es tu marca favorita? ¿Te apetece beberla en caña, botellín o jarra? ¿Buscas un plan económico?
        p CervezaYa encuentra los bares más cercanos en los que podrás disfrutar de la cerveza que quieres. Y no te preocupes por cómo ir al bar, la app te guiará.
        p Queremos que cambies tu manera de consumir cerveza: descubre nuevos sitios y consume de manera inteligente.

// Start Section 2
.section-2
  .content
    h1 La revolución del cerveceo
    .icons
      .col-md-3
        = image_tag src="love.png"
        p Encuentre tu cerveza justo como te gusta.
      .col-md-3
        = image_tag src="jarra.png"
        p Elige en qué bar quieres bebértela fresquita.
      .col-md-3
        = image_tag src="promociones.png"
        p Te mostramos las mejores ofertas de la ciudad.
      .col-md-3
        = image_tag src="irhacia.png"
        p ¡No te pierdas! Te guiamos hasta que llegues al bar.

// Section 3
.section-3
  .content
    .col-md-7
      .text-phone-second
        p.title +1000
        p.subtitle bares, pubs...
        p.title +150
        p.subtitle marcas de cerveza
        p.title OFERTAS NUEVAS
        p.subtitle todas las semanas
        p.title FRANQUICIAS
        p.subtitle 100 montaditos, Sureña...
    .col-md-4.col-md-offset-1
      .img-phone
        = image_tag "phone_2.png", class: 'phone-second'